# Generated by Django 4.2 on 2025-12-03 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='is_active',
            field=models.BooleanField(default=True, help_text="Si inactif, n'est pas compté dans les totaux"),
        ),
        migrations.AddField(
            model_name='credit',
            name='product',
            field=models.CharField(blank=True, help_text='Produit ou article vendu', max_length=100),
        ),
        migrations.AlterField(
            model_name='credit',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='credit',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('partial', 'Partiellement payé'), ('paid', 'Payé'), ('overdue', 'En retard'), ('archived', 'Archivé')], default='pending', max_length=20),
        ),
    ]
