# Generated by Django 4.2 on 2025-12-03 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Montant payé par ce boutiquier', max_digits=12),
        ),
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('active', 'Actif'), ('inactive', 'Inactif - Non payé'), ('archived', 'Archivé')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='total_owed',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Montant total dû par ce boutiquier', max_digits=12),
        ),
    ]
