# Generated by Django 4.2 on 2025-12-03 21:17

import clients.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='access_code',
            field=models.CharField(default=clients.models.generate_access_code, help_text="Code d'accès simple pour le client", max_length=10, unique=True),
        ),
    ]
