# Generated by Django 4.2 on 2025-12-03 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_access_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('active', 'Actif'), ('inactive', 'Inactif'), ('archived', 'Archivé')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='access_code',
            field=models.CharField(editable=False, help_text="Code d'accès unique et permanent", max_length=20, unique=True),
        ),
    ]
